In [1]:
import cvxpy as cp
import numpy as np
import numpy.matlib
import skimage.data
import skimage.transform
from iplabs import IPLabViewer as viewer
import matplotlib
import matplotlib.pyplot as plt
import skimage.color
%matplotlib widget
# Problem data.
m = 30
n = 20
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A*x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value)

[-1.79109255e-19  2.85112420e-02  2.79973443e-19  3.37658729e-20
 -2.72802663e-19  1.49285011e-01 -9.94082533e-20  8.35373900e-20
  2.46718649e-01  5.78224144e-01 -4.03739463e-19  1.01242860e-03
 -9.28486180e-20  2.26767464e-01 -1.58813678e-19 -8.97232272e-20
 -1.22145729e-19 -1.51509428e-19  1.12060672e-19 -3.48318635e-19]
[ 2.50938945  0.          2.78354615  1.79425782 13.08579183  0.
  0.73716363  3.35344995  0.          0.          8.93825054  0.
  7.02955161  0.          4.71068649  3.18873635  2.06090107 10.08166738
  3.0481157   8.53268239]


c:\users\dolly\documents\epfl\ma-3\project\prox_proj\lib\site-packages\cvxpy\expressions\expression.py:550: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
c:\users\dolly\documents\epfl\ma-3\project\prox_proj\lib\site-packages\cvxpy\interface\numpy_interface\ndarray_interface.py:47: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecat

In [2]:
coffee = skimage.color.rgb2gray(skimage.data.shepp_logan_phantom())
radon_coffee = skimage.transform.radon(coffee, circle = False)
rec = skimage.transform.iradon(radon_coffee, filter_name = None)
nx, ny = rec.shape 
rec = rec[ny//2-200:ny//2+200, nx//2-200:nx//2+200]
viewer([coffee, radon_coffee, rec])

c:\users\dolly\documents\epfl\ma-3\project\prox_proj\lib\site-packages\ipykernel\ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
c:\users\dolly\documents\epfl\ma-3\project\prox_proj\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The behavior of rgb2gray will change in scikit-image 0.19. Currently, rgb2gray allows 2D grayscale image to be passed as inputs and leaves them unmodified as outputs. Starting from version 0.19, 2D arrays will be treated as 1D images with 3 channels.
  """Entry point for launching an IPython kernel.


Button(description='Show Widgets', style=ButtonStyle())

In [3]:
vector = np.zeros((10,))
vector[0] = 1
vector[1] = -1
vector[2] = -1

def circular(x):
    idx = np.arange(len(x))
    Q = np.matlib.repmat(x, len(x),1)
#     circular = np.apply_along_axis(lambda x, idx: np.roll(x, idx)
    for i, row in enumerate(Q):
        Q[i] = np.roll(row, i)
    return Q
    
Q = circular(vector)
Q
# Q@Q.T
# v = np.random.normal(size = (10,))
# print(v)
# print((Q@v)[:-1])
# print(v[1:] - v[:-1])

array([[ 1., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -1., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -1., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1.],
       [-1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [4]:
np.matlib

<module 'numpy.matlib' from 'c:\\users\\dolly\\documents\\epfl\\ma-3\\project\\prox_proj\\lib\\site-packages\\numpy\\matlib.py'>

# Obsolete Code

In [5]:
# TV (1D) matrix generation 
#     # Declare Finite Differences
vector = np.zeros((n,))
vector[0] = 1
vector[1] = -1
idx = np.arange(n)
Q = np.matlib.repmat(vector, n, 1)
for i, row in enumerate(Q):
    Q[i] = np.roll(row, i)
    
# Declare LoG Matric
vector = np.zeros((n,))
vector[0] = 1
vector[1] = -2
vector[2] = 1
idx = np.arange(n)
Q = np.matlib.repmat(vector, n, 1)
for i, row in enumerate(Q):
    Q[i] = np.roll(row, i)

# Quick tests on finite differences matrices
x = np.arange(6*7).reshape((6, 7))**2
# print(A)
# print('Horizontal direction')
# print((A[:, 1:] - A[:, :-1])[:-1, :])
# print('Vertical direction')
# print((A[1:, :] - A[:-1, :])[:, :-1])

D1 = (x[:, 1:] - x[:, :-1])
D2 = (x[1:, :] - x[:-1, :])
# D11 = (D1[:, 1:] - D1[:, :-1])[:-1, :]
# D22 = (D2[1:, :] - D2[:-1, :])[:, :-1]
# D21 = (D2[:, 1:] - D2[:, :-1])[:-1, :]
# D12 = (D1[1:, :] - D1[:-1, :])[:, :-1]
print(x, x.shape)
print(D1, D1.shape)
print(D2, D2.shape)
print()
# print(D11, D11.shape)
# print(D22, D22.shape)
# print(D21, D21.shape)
# print(D12, D12.shape)

[[   0    1    4    9   16   25   36]
 [  49   64   81  100  121  144  169]
 [ 196  225  256  289  324  361  400]
 [ 441  484  529  576  625  676  729]
 [ 784  841  900  961 1024 1089 1156]
 [1225 1296 1369 1444 1521 1600 1681]] (6, 7)
[[ 1  3  5  7  9 11]
 [15 17 19 21 23 25]
 [29 31 33 35 37 39]
 [43 45 47 49 51 53]
 [57 59 61 63 65 67]
 [71 73 75 77 79 81]] (6, 6)
[[ 49  63  77  91 105 119 133]
 [147 161 175 189 203 217 231]
 [245 259 273 287 301 315 329]
 [343 357 371 385 399 413 427]
 [441 455 469 483 497 511 525]] (5, 7)



In [8]:
a = np.random.normal(size = (2, 4,))
a.reshape(-1)

array([-1.89881206, -1.11711069, -0.50897228, -0.16648595,  1.42361443,
        0.90399917,  1.57546791,  1.2066079 ])

In [6]:
import scipy.linalg

In [7]:
v = np.random.normal(20, 20)
x = cp.Variable((20, 20), nonneg = True)

# Defining D1 and D2x We loose one element in the *other* dimension to account for the lost element and have elements of equal size
D1 = (x[:, 1:] - x[:, :-1])[:-1, :]
D2 = (x[1:, :] - x[:-1, :])[:, :-1]
D11 = (D1[:, 1:] - D1[:, :-1])[:-1, :]
D22 = (D2[1:, :] - D2[:-1, :])[:, :-1]
D21 = (D2[:, 1:] - D2[:, :-1])[:-1, :]
D12 = (D1[1:, :] - D1[:-1, :])[:, :-1]
#     T = D11 + D22
#     D = cp.multiply(D11, D22) - cp.multiply(D12, D21)
#     lamb_1 = T/2 + cp.multiply((T)**2, cp.power(4 - D, -1))
#     lamb_2 = T/2 - cp.multiply((T)**2, cp.power(4 - D, -1))
#     y = cp.Variable((nx*ny, 2, 2))
#     y[:, 0, 0] = cp.vec(D11)
#     y[:, 0, 1] = cp.vec(D12)
#     y[:, 1, 0] = cp.vec(D21)
#     y[:, 1, 1] = cp.vec(D22)
D11 = cp.vec(D11)
D12 = cp.vec(D12)
D21 = cp.vec(D21)
D22 = cp.vec(D22)
inner = 0
for i in range(400):
#         y = cp.Variable((2, 2))
#         y[0, 0] = D11[i]
#         y[0, 1] = D12[i]
#         y[1, 0] = D21[i]
#         y[1, 1] = D22[i]
    a = [[D11[i], D12[i]], [D21[i], D22[i]]]
    eig = scipy.linalg.eigvals(a)
    inner = inner + eig[0] + eig[1]# cp.sum_largest(scipy.linalg.eigvals(a), 2) 

#     obj = cp.pnorm(lamb_1 + lamb_2, 1) + cp.sum_squares(x - v)/(2*lamb)
obj = inner + cp.sum_squares(x - v)/(2*lamb)


prob = cp.Problem(cp.Minimize(obj))
prob.solve()

ValueError: object arrays are not supported

In [ ]:
# type(cp.expressions.leaf.Leaf((2, 2), a))
# x = [[D11[i], D12[i]], [D21[i], D22[i]]]
y = cp.expressions.leaf.Leaf((2, 2), constant = False)
y.value = D11[i]

In [ ]:
dir(cp.lambda_sum_largest.get_data)

In [17]:
import numpy as np
import matplotlib.pyplot as plt
plt.close('all')

x = np.linspace(-5,5,1000) 
gammas = [0.01, 0.1, 0.5, 1, 2]

plt.figure()
for gamma in gammas:
    moreau = np.zeros_like(x)
    # Pol's version
#     moreau[x>0] = x[x>0]**2/(gamma+1)**2 * (gamma/2. +1./2.)
    moreau[x>0] = x[x>0]**2/(2*(gamma+1))
    # My version
#     moreau[x>0] = x[x>0]**2*(1. + gamma)/(2.*gamma)
    # Untouched version
#     moreau[x>0] = x[x>0]**2 + x[x>0]**2/(2*gamma)
    # Negative side
    moreau[x<0] = x[x<0]**2/(2*gamma)
#     moreau = 2*np.abs(x)-1
#     moreau = np.abs(x)
    
    plt.plot(x,moreau,label=f"$f_{{{gamma}}}(x)$")
plt.plot(x[x>=0],x[x>=0]**2/2,'k',label=r"$f(x) = x^2/2 + \delta_{\mathbb{R}_+}(x)$")
# plt.plot(x, x**2)
plt.legend()
plt.axis((-5,5,0,25))
plt.xticks(np.arange(-5, 5))
plt.yticks(np.arange(0, 25, 2))
plt.xlabel('$\mathbf{v}$')
plt.ylabel('$\operatorname{M}_{\lambda f}(\mathbf{v})$')
plt.grid()
plt.title('Moreau envelope $\operatorname{M}_{\lambda f}(\mathbf{v})$ of $f(\mathbf{v}) = x^2/2 + \delta_{\operatorname{R}^+}(x)$ ')

c:\users\dolly\documents\epfl\ma-3\project\prox_proj\lib\site-packages\ipykernel\ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<>:30: DeprecationWarning: invalid escape sequence \m
<>:31: DeprecationWarning: invalid escape sequence \o
<>:33: DeprecationWarning: invalid escape sequence \o
<>:30: DeprecationWarning: invalid escape sequence \m
<>:31: DeprecationWarning: invalid escape sequence \o
<>:33: DeprecationWarning: invalid escape sequence \o
<>:30: DeprecationWarning: invalid escape sequence \m
<>:31: DeprecationWarning: invalid escape sequence \o
<>:33: DeprecationWarning: invalid escape sequence \o
<ipython-input-17-fac77fae2364>:30: DeprecationWarning: invalid escape sequence \m
  plt.xlabel('$\mathbf{v}$')
<ipython-input-1

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Pan', 'Pan axes with left…

Text(0.5, 1.0, 'Moreau envelope $\\operatorname{M}_{\\lambda f}(\\mathbf{v})$ of $f(\\mathbf{v}) = x^2/2 + \\delta_{\\operatorname{R}^+}(x)$ ')

In [ ]:
plt.figure()
x = np.linspace(-5,5,1000) 
gammas = [1, 2, 3]
v = 4
ax = plt.gca()
for gamma in gammas:
    proximal = np.zeros_like(x)
    # Pol's version
    proximal = np.abs(x) + (x-v)**2/(2*gamma)
    opt = np.where(proximal == np.min(proximal))[0][0]
    color = next(ax._get_lines.prop_cycler)['color']
    plt.plot(x[opt], proximal[opt], 'o', color = color)
    plt.plot(x,proximal,label=r"$f(x) + \frac{1}{2\gamma}\|x_v\|_2^2$" + f', $\gamma$ = {gamma}', color = color)
#     if gamma == 3:
#         plt.plot(x[opt], proximal[opt], 'rx', label = r'$\mathrm{min}$')
#     plt.plot(x,proximal,label=f"$prox_{f_{{{gamma}}}}(x)$")
plt.plot(x, np.abs(x), 'k', label=r"$f(x) = |x|$")
# plt.axvline(4, 'r--', label = '$v$')
plt.axvline(4, color='r', ls = '--', linewidth=0.5, label='$v$')
# plt.plot(x, x**2)
plt.legend()
plt.axis((-5,5,0,25))
plt.ylim([0, 10])
plt.xticks(np.arange(-5, 5))
# plt.yticks(np.arange(0, 5, 1))
plt.xlabel('$x$')
plt.ylabel('$f(x)$')
plt.grid()
plt.title(r'Proximal Minimization Algorithm ($f = |x|$, $v = 4$)')

In [8]:
np.where(proximal == np.min(proximal))[0][0]

NameError: name 'proximal' is not defined

In [9]:
import numpy
N = 501    # Note: Use 501 instead of 500 to avoid the zero value
d = numpy.finfo(numpy.float32).eps * 1e4
a = 3.0
x = a * numpy.ones(N, dtype=numpy.float32)
y = [x[i] + numpy.multiply((i - numpy.divide(N, 2.0, dtype=numpy.float32)), d, dtype=numpy.float32) for i in range(N)]

# Compute errors and "true" error
relative_error = numpy.empty((2, N), dtype=numpy.float32)
relative_error[0, :] = numpy.abs(x - y) / x
relative_error[1, :] = numpy.abs(1.0 - y / x)
exact = numpy.abs( (numpy.float64(x) - numpy.float64(y)) / numpy.float64(x))

# Compute differences between error calculations
error = numpy.empty((2, N))
for i in range(2):
    error[i, :] = numpy.abs((relative_error[i, :] - exact) / numpy.abs(exact))

fig = plt.figure()
axes = fig.add_subplot(1, 1, 1)
axes.semilogy(y, error[0, :], '.', markersize=10, label="$|x-y|/|x|$")
axes.semilogy(y, error[1, :], '.', markersize=10, label="$|1-y/x|$")

axes.grid(True)
axes.set_xlabel("y")
axes.set_ylabel("Relative Error")
axes.set_xlim((numpy.min(y), numpy.max(y)))
axes.set_ylim((5e-9, numpy.max(error[1, :])))
axes.set_title("Relative Error Comparison")
axes.legend()
plt.show()

fig = plt.figure()
axes = fig.add_subplot(1, 1, 1)
axes.plot(x)
axes.plot(y)

axes.grid(True)
# axes.set_xlabel("y")
# axes.set_ylabel("Relative Error")
# axes.set_xlim((numpy.min(y), numpy.max(y)))
# axes.set_ylim((5e-9, numpy.max(error[1, :])))
# axes.set_title("Relative Error Comparison")
# axes.legend()
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Pan', 'Pan axes with left…

c:\users\dolly\documents\epfl\ma-3\project\prox_proj\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
c:\users\dolly\documents\epfl\ma-3\project\prox_proj\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Pan', 'Pan axes with left…